# Generated by Django 5.2.17 on 2026-08-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True)),
                ('order_type', models.CharField(choices=[('RETAIL', 'Retail B2C'), ('WHOLESALE', 'Wholesale B2B')], default='RETAIL', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('STOCK_LOCKED', 'Stock Locked / Approved'), ('PACKING', 'In Packing'), ('DISPATCHED', 'Dispatched on Vehicle'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30)),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI (GPay / PhonePe / Paytm)'), ('CREDIT_KHAATA', 'B2B 15/30 Day Credit Khaata'), ('COD', 'Cash On Delivery'), ('NETBANKING', 'Net Banking / Bank Transfer')], default='UPI', max_length=30)),
                ('total_gross_weight_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('delivery_address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_primary_bales', models.IntegerField(default=1)),
                ('qty_secondary_pcs', models.IntegerField(default=500)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
