# Generated by Django 5.2.17 on 2026-08-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FleetTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_code', models.CharField(max_length=50, unique=True)),
                ('dispatch_order_id', models.CharField(blank=True, max_length=100)),
                ('origin', models.CharField(default='Krishna Trading Warehouse', max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('total_gross_weight_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('start_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('end_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pod_signature_url', models.CharField(blank=True, max_length=500)),
                ('pod_otp_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DISPATCHED', 'Dispatched'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered (POD Signed)')], default='DISPATCHED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FleetVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(max_length=30, unique=True)),
                ('vehicle_type', models.CharField(choices=[('ACTIVA', 'Activa / Scooter (Up to 50 Kg)'), ('CHHOTA_HATHI', 'Chhota Hathi / Tata Ace (Up to 500 Kg)'), ('TEMPO', 'Heavy Tempo (Up to 1,000 Kg / 1 Ton)'), ('TRUCK', 'Heavy Export Truck (1 Ton+)')], max_length=30)),
                ('payload_capacity_kg', models.DecimalField(decimal_places=2, default=500.0, max_digits=8)),
                ('puc_expiry', models.DateField(blank=True, null=True)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('fitness_expiry', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fuel_liters', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cost_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_photo_url', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
