# Generated by Django 5.2.17 on 2026-08-07 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('hsn_code', models.CharField(default='3923', max_length=20)),
                ('primary_unit', models.CharField(choices=[('BALE', 'Bale / Master Bundle'), ('CARTON', 'Corrugated Master Carton')], default='BALE', max_length=20)),
                ('secondary_unit', models.CharField(choices=[('PCS', 'Pieces / Bags'), ('KG', 'Kilograms')], default='PCS', max_length=20)),
                ('conversion_rate', models.IntegerField(default=500, help_text='e.g. 1 Bale = 500 Pieces')),
                ('unit_weight_kg', models.DecimalField(decimal_places=2, default=65.0, help_text='Weight of 1 Primary Unit in Kg', max_digits=8)),
                ('retail_price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_stock_alert', models.IntegerField(default=5)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
        ),
    ]
