# Generated by Django 5.2.17 on 2026-08-07 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing', '0001_initial'),
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractpricing',
            name='wholesale_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_prices', to='users.wholesaleprofile'),
        ),
        migrations.AddField(
            model_name='wholesalepricetier',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='products.product'),
        ),
    ]
