# Generated by Django 5.2.17 on 2026-08-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('reference_no', models.CharField(max_length=100)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Bill Amount Added', max_digits=12)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Payment Received', max_digits=12)),
                ('running_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Outstanding Balance', max_digits=12)),
            ],
        ),
    ]
